src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"title"},
 * message="Une autre annonce a déjà ce titre, veuillez en changer")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,max=255,minMessage="Le titre doit faire + de 10 caractères",maxMessage="Votre titre est trop long, pas plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=30,minMessage="Merci de mettre au moins 30 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=30,minMessage="Merci de mettre au moins 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad",orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Création d'un fonction pour permettre d'initialiser le slug (avant la persistance et avant la maj)
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * 
     */

    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }
    
    public function getAverageRatings(){
        // calcul de la somme des notes
        $sum = array_reduce($this->comments->toArray(),function($total,$comment){
            // on retourne le total + la onte de chaque commentaires
            return $total + $comment->getRating();
        },0);
        
        // diviser le total par le nombre de notes
        if(count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }

    public function getNotAvailableDays(){
        $notAvailableDays = [];

        foreach($this->bookings as $booking){
            $resultat = range(
                $booking -> getStartDate()->getTimestamp(),
                $booking -> getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
        
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            },$resultat);

            $notAvailableDays = array_merge($notAvailableDays,$days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="un autre utilisateur s'est déjà inscrit avec adresse mail")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url()
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * Comparaison du champ ci dessous avec hash
     *
     * @Assert\EqualTo(propertyPath="hash",message="les 2 mots de passe ne correspondent pas.")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="Votre intro doit comporter au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100,minMessage="Votre description doit comporter au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName(){
        return"{$this->firstname} {$this->lastname}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Création d'un fonction pour permettre d'initialiser le slug (avant la persistance et avant la maj)
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * 
     */

    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstname. ' '.$this->lastname);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash= $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

public function getRoles(){

$roles = $this->userRoles->map(function($role){
    return $role->getTitle();
})->toArray();

$roles[]= 'ROLE_USER';

    return $roles;
}

public function getPassword(){
    return $this->hash;
}
public function getSalt(){}
public function getUsername(){
    return $this->email;
}
public function eraseCredentials(){}

/**
 * @return Collection|Role[]
 */
public function getUserRoles(): Collection
{
    return $this->userRoles;
}

public function addUserRole(Role $userRole): self
{
    if (!$this->userRoles->contains($userRole)) {
        $this->userRoles[] = $userRole;
        $userRole->addUser($this);
    }

    return $this;
}

public function removeUserRole(Role $userRole): self
{
    if ($this->userRoles->contains($userRole)) {
        $this->userRoles->removeElement($userRole);
        $userRole->removeUser($this);
    }

    return $this;
}

/**
 * @return Collection|Booking[]
 */
public function getBookings(): Collection
{
    return $this->bookings;
}

public function addBooking(Booking $booking): self
{
    if (!$this->bookings->contains($booking)) {
        $this->bookings[] = $booking;
        $booking->setBooker($this);
    }

    return $this;
}

public function removeBooking(Booking $booking): self
{
    if ($this->bookings->contains($booking)) {
        $this->bookings->removeElement($booking);
        // set the owning side to null (unless already changed)
        if ($booking->getBooker() === $this) {
            $booking->setBooker(null);
        }
    }

    return $this;
}

/**
 * @return Collection|Comment[]
 */
public function getComments(): Collection
{
    return $this->comments;
}

public function addComment(Comment $comment): self
{
    if (!$this->comments->contains($comment)) {
        $this->comments[] = $comment;
        $comment->setAuthor($this);
    }

    return $this;
}

public function removeComment(Comment $comment): self
{
    if ($this->comments->contains($comment)) {
        $this->comments->removeElement($comment);
        // set the owning side to null (unless already changed)
        if ($comment->getAuthor() === $this) {
            $comment->setAuthor(null);
        }
    }

    return $this;
}

}

templates/ad/_ad.html.twig
{% set url= path('ads_single',{'slug':ad.slug}) %}
            <div class="col-md-4 mt-3">
                <div class="card">
                    <div class="card-header bg-primary text-light">{{ad.rooms}} chambres pour <strong>{{ad.price}}&euro;</strong> /nuit</div>
                        <div class="card-body">
                            <a href="{{url}}">
                                <img src="{{ad.coverImage}}" class="img-fluid" alt="{{ad.title}}" style="height:200px;width:100%;display:block;">
                            </a>
                            <h4 class="card-title">{{ad.title}}</h4>
                            <p class="card-text">{{ad.introduction}}</p>
                            <a href="{{url}}" class="btn btn-outline-secondary">+ d'infos</a>
                            {% if app.user and app.user == ad.author %}
                                <a href="{{path('ads_edit',{'slug':ad.slug})}}" class="btn btn-outline-warning">Modifier</a>
                                <a href="{{path('ads_delete',{'slug':ad.slug})}}" class="btn btn-outline-danger" onclick="return confirm(`Etes vous sûr de vouloir supprimer cette annonce ?`)">Supprimer</a>
                            {% endif %}
                        </div>
                        <div class="card-footer text-muted text-center">
                            {% if ad.comments | length > 0 %}
                                {% include 'inc/rating.html.twig' with {'rating' : ad.averageRatings} %} sur {{ ad.comments | length}} avis.
                            {% else %}
                                <span>Pas encore de commentraire.</span>
                            {% endif %}
                        </div>
                </div>
            </div>

templates/ad/_collections.html.twig
{% block _annonce_images_widget %}

    <p>ici vous pouvez insérer des images supplémentaires</p>
    <input type="hidden" id="widget-count" value="0">
    <button type="button" class="btn btn-secondary" id="add-image">Ajouter un image</button>

    {{form_widget(form)}}

{% endblock %}


{% block _annonce_images_entry_row %}

    {{form_widget(form)}}

{% endblock %}

{% block _annonce_images_entry_widget %}

    <div class="form-group" id="bloc_{{id}}">
        <div class="row">
            <div class="col-md-10 col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-2">
            <button type="button" class="btn btn-danger" data-action="delete" data-target="#bloc_{{id}}"><i class="fas fa-trash-alt"></i></button>
            </div>
        </div>
        
    </div>

{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifier une annonce {% endblock %}

{% form_theme form 'ad/_collections.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Modification d'une annonce</h1>

        {{ form_start(form) }}

            {{ form_widget(form) }}

            <button type="submit" class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}

    </div>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les annonces{% endblock %}

{% block body %}

    <main class="container">
        <h1 class="mt-5 mb-3">{{ controller_name }}</h1>
        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </main>

{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'ad/_collections.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Création d'une nouvelle annonce</h1>

        {{ form_start(form) }}

            {{ form_widget(form) }}

            <button type="submit" class="btn btn-primary">Créer</button>

        {{ form_end(form) }}


    </div>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ad.title}}{% endblock %}
{% block body %}

    <div class="card-title" style="background-image:url({{ad.coverImage}});">

        <div class="container">
            <h1>{{ad.title}}</h1>
            <p>{{ad.introduction}}</p>
            <p class="h5">{{ad.rooms}} chambres pour <strong>{{ad.price}} €</strong> / nuit</p>        
            <a href="{{path('booking_create',{'slug':ad.slug})}}" class="btn btn-outline-success">Réserver !</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{path('ads_edit',{'slug':ad.slug})}}" class="btn btn-outline-warning">Modifier</a>
                <a href="{{path('ads_delete',{'slug':ad.slug})}}" class="btn btn-outline-danger" onclick="return confirm(`Etes vous sûr de vouloir supprimer cette annonce ?`)">Supprimer</a>
            {% endif %}
            
        </div>

    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content|raw}}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{loop.index0}}" class="{% if loop.first %}active{% endif %}"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src="{{image.url}}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ad.title}}</h5>
                                <p>{{image.caption}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Précédent</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Suivant</span>
                    </a>
                </div>            

                <hr>

                {% if ad.comments | length > 0 %}
                    <h3>Commentaires des voyageurs</h3>
                    <div class="alert alert-info">
                        <h4 class="alert-heading h6">
                            <div class="row align-items-center">
                                <div class="col-md-7">
                                    Note glodale donnée par les voyageurs : 
                                </div>
                                <div class="col-5">
                                    {% include 'inc/rating.html.twig' with {'rating' : ad.averageRatings} %} <br>    
                                    <small>Moyenne est calculé sur {{ad.comments | length }} avis.</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light-rounded">
                            <p><strong>{{comment.author.fullname}}</strong> a dit : </p>
                            <blockquote>{{comment.content}}</blockquote>
                            <p>Note donnée : 
                                {% include 'inc/rating.html.twig' with {'rating' : comment.rating} %}
                            </p>
                        </div>
                    {% endfor %}
                {% else %}
                    <h3>Cette annonce n'a pas de commentaire.</h3>
                {% endif %}
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-4">
                        <a href="{{path('user_show',{'slug':a.slug})}}">
                            <img src="{{ a.avatar }}" alt="{{ a.fullName }}" class="avatar avatar-medium">
                        </a>
                    </div>
                    <div class="col">
                        <a href="{{path('user_show',{'slug':a.slug})}}">
                        <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-warning">{{ a.ads | length }}{% if a.ads | length >1 %} annonces {% else %} annonce {% endif %}</span>
                    </div>
                </div>
                <div class="col py-3">
                    {{ a.introduction | raw}}
                </div>
                
            </div>
        </div>
    </div>

{% endblock %}